/**:
  ros__parameters:
    wheel_radius: 0.529
    wheel_width: 0.279
    wheel_base: 5.3
    wheel_tread: 2.065
    front_overhang: 2.8 #pcd crop -0.50
    rear_overhang: 2.83 #pcd crop + 0.07
    left_overhang: 0.25 #pcd crop + 0.13
    right_overhang: 0.25 #pcd crop + 0.13
    vehicle_height: 3.1
    max_steer_angle: 0.785

    # original
    # wheel_radius: 0.529
    # wheel_width: 0.279
    # wheel_base: 5.3
    # wheel_tread: 2.065
    # front_overhang: 2.255
    # rear_overhang: 2.83
    # left_overhang: 0.21
    # right_overhang: 0.21
    # vehicle_height: 3.096
