# logger_config.yaml

# ============================================================
# planning
# ============================================================

behavior_path_planner:
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner
    logger_name: planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner
    logger_name: tier4_autoware_utils

behavior_path_planner_avoidance:
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner
    logger_name: planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.avoidance

behavior_path_planner_lane_change:
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner
    logger_name: lane_change

behavior_velocity_planner:
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner
    logger_name: planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner
    logger_name: tier4_autoware_utils

behavior_velocity_planner_intersection:
  - node_name: /planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner
    logger_name: planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.intersection

motion_obstacle_avoidance:
  - node_name: /planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner
    logger_name: planning.scenario_planning.lane_driving.motion_planning.obstacle_avoidance_planner
  - node_name: /planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner
    logger_name: tier4_autoware_utils

motion_velocity_smoother:
  - node_name: /planning/scenario_planning/motion_velocity_smoother
    logger_name: planning.scenario_planning.motion_velocity_smoother
  - node_name: /planning/scenario_planning/motion_velocity_smoother
    logger_name: tier4_autoware_utils

# ============================================================
# control
# ============================================================

lateral_controller:
  - node_name: /control/trajectory_follower/controller_node_exe
    logger_name: control.trajectory_follower.controller_node_exe.lateral_controller
  - node_name: /control/trajectory_follower/controller_node_exe
    logger_name: tier4_autoware_utils

longitudinal_controller:
  - node_name: /control/trajectory_follower/controller_node_exe
    logger_name: control.trajectory_follower.controller_node_exe.longitudinal_controller
  - node_name: /control/trajectory_follower/controller_node_exe
    logger_name: tier4_autoware_utils

vehicle_cmd_gate:
  - node_name: /control/vehicle_cmd_gate
    logger_name: control.vehicle_cmd_gate
  - node_name: /control/vehicle_cmd_gate
    logger_name: tier4_autoware_utils
