/**:
  ros__parameters:
    marker_color: ["FF0000", "FF5A00", "FFFF00"]
    marker_color_dist_thresh : [0.1, 0.2, 0.3]
    output_trajectory_interval: 1.0

    validation:
      dist_threshold_to_road_border: 0.0
      max_steer_angle_margin: 0.0 # [rad] NOTE: Positive value makes max steer angle threshold to decrease.
