/**:
  ros__parameters:
    # Course Specific Parameters
    velocity_on_curve: 3.5
    stopping_distance: 15.0
    course_width: 1.5
    smoothing_window: 100
    length_of_straight_line: 50.0
    longitude: 139.6503
    latitude: 35.6762

    # Data Collection Range
    COLLECTING_DATA_V_MIN: 0.5
    COLLECTING_DATA_V_MAX: 8.0
    COLLECTING_DATA_A_MIN: -1.0
    COLLECTING_DATA_A_MAX: 1.0

    # Noise Parameters
    longitudinal_velocity_noise_amp: 0.01
    longitudinal_velocity_noise_min_period: 5.0
    longitudinal_velocity_noise_max_period: 20.0

    acc_noise_amp: 0.01
    acc_noise_min_period: 5.0
    acc_noise_max_period: 20.0

    steer_noise_amp: 0.01
    steer_noise_min_period: 5.0
    steer_noise_max_period: 20.0
