name: spell-check-partial

on:
  pull_request:

jobs:
  spell-check-partial:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run spell-check
        uses: autowarefoundation/autoware-github-actions/spell-check@v1
        with:
          cspell-json-url: https://raw.githubusercontent.com/autowarefoundation/autoware-spell-check-dict/main/.cspell.json
          local-cspell-json: .cspell-partial.json
          incremental-files-only: false
